server:
  port: ${PORT:9192}

spring:
#  profiles:
#    active: ${SPRING_PROFILE:local} Can be used for deployment on diff env.
  application:
    name: statementapi
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://vmfsbcgqujxhbedjlzhk.supabase.co/auth/v1/.well-known/jwks.json
          jws-algorithms: ES256 #supabase
  datasource:
    url: jdbc:postgresql://localhost:5432/statementsdb
    driver-class-name: org.postgresql.Driver
    username: rootuser
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000   # 30 seconds
      connection-timeout: 30000
      pool-name: MyHikariCP
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

statement:
  shed-lock-table: "shedlock"
  s3-integration:
    supabase-s3-config:
      endpoint: "https://vmfsbcgqujxhbedjlzhk.storage.supabase.co/storage/v1/s3"   # Must be s3 endpoint
      region: "us-east-1"                                         # Supabase forces us-east-1
      access-key: "487c261456c020f16e137f5934c6cc4f"
      secret-key: "da779bb492a8586e42634639430107650010fa32c2322f2e62ee16dd27d307d1"
    bucket: "account-statements"
    signed-expiration: PT1H
scheduler:
  cron:
    delete-pending-uploads: 0 0 * * * *



springdoc:
  api-docs:
    path: /swagger-ui/info #Serves OpenAPI document from this path.
  swagger-ui:
    disable-swagger-default-url: true #Do not show default swagger
    url: /swagger-ui/info
    path: /api/swagger-ui

logging:
  level:
    root: INFO