server:
  port: 9192
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https:supabase.co/auth/v1/certs #supabase
  datasource:
    url: jdbc:postgresql://localhost:3306/statementsdb
    driver-class-name: org.postgresql.Driver
    username: rootuser
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000   # 30 seconds
      connection-timeout: 30000
      pool-name: MyHikariCP
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    schema: statementsdb
    baseline-on-migrate: true

statementapi:
  all-words:
    word-limit: 1000
  word-limit: 10


springdoc:
  api-docs:
    path: /swagger-ui/info #Serves OpenAPI document from this path.
  swagger-ui:
    disable-swagger-default-url: true #Do not show default swagger
    url: /swagger-ui/info
    path: /api/swagger-ui

logging:
  level:
    root: INFO