name: CI / CD to Render

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build & Test
        run: mvn -B clean verify

#  deploy:
#    name: Deploy to Render
#    needs: build-test
#    runs-on: ubuntu-latest
#
#    # Only run deploy if branch is develop or main
#    if: |
#      github.ref == 'refs/heads/develop' ||
#      github.ref == 'refs/heads/main'
#
#    steps:
#      - name: Select Render deploy hook based on branch
#        id: set-hook
#        run: |
#          if [ "${GITHUB_REF##*/}" = "develop" ]; then
#            echo "hook=${{ secrets.RENDER_STAGING_HOOK }}" >> $GITHUB_OUTPUT
#            echo "Deploying to Render STAGING..."
#          else
#            echo "hook=${{ secrets.RENDER_PROD_HOOK }}" >> $GITHUB_OUTPUT
#            echo "Deploying to Render PRODUCTION..."
#          fi
#
#      - name: Trigger Render Deployment
#        run: |
#          curl -X POST "${{ steps.set-hook.outputs.hook }}"
